name: deoldify
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pytorch<=2.5.1
  - torchvision<=0.20.1
  - pytorch-cuda=12.1  # CUDA runtime cho GPU
  - ffmpeg
  - pip
  - pip:
      - deoldify
      - imageio
      - matplotlib
      - scipy
      - pandas
      - fastprogress
      - fastapi
      - python-multipath
      - uvicorn